### ISSUE TITLE
CI integration and unit test

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#20]
**Is your feature request related to a problem? Please describe.**
No unit test for now. #21 
How to emulate a USB device ? Use of a good mock without the emulation of the communication (integration tests)

**Describe the solution you'd like**
Even without unit tests, insure compile and lint task on each commit with a dockerfile associate and running on a job

Candidate CI : gitlab, jenkins, travis ?

**Describe alternatives you've considered**
You can't escape CI :)

**Additional context**
Use of a CI dedicated file for the job (usually placed on the root directory or script directory)

**Comment by Stormiix** [comment]
I don't think will need to emulate a USB device, unless we need to test the bluerobotics-ping library. 
We currently have a working emulator script that allows us to try the package without the sonar (by setting the env variable to "true"), but it only outputs random data, once it's done, it could be used to run tests.

Since we're on github, we could make use of their new CI pipeline, Github Actions, it looks quite easy to setup, but I've never used it. If not, travis-ci, is also a good alternative, they have a free offer for open source projects we could use.

We currently have some other few bugs we need to fix on the develop branch, but I think the next step would be to automate linting and compiling using CI.

Thanks again @tomlogan501 for the awesome suggestions, we are grateful for your help :smile:
