### ISSUE TITLE
Remove previous angle scan

### ISSUE THREAD

**Issue by tomlogan501** [CentraleNantesRobotics/ping360_sonar#49]
**Is your feature request related to a problem? Please describe.**
The topic scan is a merge of scans done at different time (Sonar rate is very slow)
Therefore the output topic is not reliable

**Describe the solution you'd like**
Just provide the current angle scan

**Describe alternatives you've considered**
Another possibility would be to create a new type of message like laserscanTimestamped but too much work.

**Comment by Stormiix** [comment]
If we remove the previous scan angles, the node will only publish a single value ranges array containing the measured range at the current angle scan. 

Would that behavior be acceptable ? (I haven't used the LaserScan sensors before so I wonder if a single measure per message is the expected behavior)

**Comment by tomlogan501** [comment]
I think this is acceptable, then you should use it like me with laser_assembler.
