### ISSUE TITLE
trigger sonar slow

### ISSUE THREAD

**Issue by linzha0** [CentraleNantesRobotics/ping360_sonar#76]
Hi, thanks for sharing this awesome project. Currently, We modified your code from ROS2 to ROS1 for our vehicle. Basically, just replace the ROS2 wrap, the interface code is same and it works well. The code is [here](https://github.com/GSO-soslab/bluerobotics_ping360)

But we found a issue that sonar trigger is kind of slow. For basic setup, it takes nearly 48 second to rotate 360 degree, the ping-viewer takes 6 seconds in same configuration. we tested the sonar in a trash can within water. 

we found `sonar.waitMessage(Ping360Id::DEVICE_DATA, 8000)` from `sonar_interface/Ping360Interface::read()` will take about 0.11 second. maybe that's the problem. when we reduce timeout less then 300, it become faster but lost some data.

We just wondering if you have conditions like this before. If you could give us some suggestions, it will be great. thanks for the help.

**Comment by AlexisFetet** [comment]
Hi,

Thanks for your interest.
We are currently using [this](https://github.com/GSO-soslab/ping-cpp/blob/14183a9d6cd484f7009f174fc88c8efa1c458c8a/src/device/ping-device.cpp) definition of the function, I am usure if this is the reason for the performance gap as this part is ROS independant. 
I noticed that you are using the same timeout value for your ROS version (`sonar.waitMessage(Ping360Id::DEVICE_DATA, 8000)`), did this still improve performance?

I am personnally not able to perform testing on an actual sonar, however I'm interested in knowing what part is actually taking this much time. Did you try timing each major function as you did with the `waitMessage`? This would help knowing where to focus our attention in the first place.

**Comment by AlexisFetet** [comment]
Regarding the timeout, I created a request to add it as parameter for more customizability. #77

**Comment by linzha0** [comment]
I did a little test for those functions, we can see `sonar.waitMessage` cost all the time. this time I test in the air.
>[sonar.set_transducer ]: 0.0000 seconds
[sonar.waitMessage with 300 timeout]: 0.1288 seconds
[sonar_->read()]: 0.1289 seconds
[ros publish]: 0.0000 seconds
[Total: refresh()]: 0.1289 seconds

**Comment by oKermorgant** [comment]
Hi, 

The PR was just merged, we still need to do tests with the sonar.
Up to now we have mainly focused on the configuration / communication / display.

**Comment by Rezenders** [comment]
Hi,

Just to want to add some info into this discussion about a similar but different situation.
I was running this package inside a docker image in the bluerov's raspberry pi. Like this: 

`docker run --name=ping360_sonar -it --rm --privileged -v /dev:/dev rezenders/bluerov_ping360:foxy ros2 run ping360_sonar ping360_node`

The sonar readings were super slow. I tried changing the timeout parameter but it would result in the program not being able to read from the sonar.
I figured out that the reason for this is that there is a bridge between `/dev/ttyUSB0` and `0.0.0.0:9092`. This was making the port busy, but for some reason the container was not able to identify that the port was busy (probably need to mount other linux folders into the container for it to recognize). After killing the bridge it worked as expected.

However, in my opinion is not ideal to kill the bridge service. I guess the best alternative is to run the package in the laptop connected with the tether and open the udp port. Like I asked in issue #78. I will try to make it work.

**Comment by AlexisFetet** [comment]
Hi, 
@linzha0, @Rezenders, would it be possible to have more information about the hardware you tested the node on? And possibly provide the CPU and RAM load during the tests, as well as other running programs during said tests?

**Comment by ES-Alexander** [comment]
@Rezenders (/ @AlexisFetet )

> I figured out that the reason for this is that there is a bridge between `/dev/ttyUSB0` and `0.0.0.0:9092`.

Assuming you're using [BlueOS](https://github.com/bluerobotics/BlueOS-docker) on your Raspberry Pi, that will be from [the `ping` service](https://github.com/bluerobotics/BlueOS-docker/tree/master/core/services/ping) which is made to look for serial Ping devices and set up bridges to allow them to be accessed via UDP (including from the topside).

Since you've managed to get a UDP connection working with ROS, did that help with your speeds?

---

More generally on the speed front, the scan speed depends on the scan parameters (e.g. longer distances and finer angular resolution take longer), as well as the speed of the I/O to send and receive messages (at both the physical and software levels - ethernet is faster than USB, and C++ is faster than Python).

To find out what speeds you can expect it may be worth connecting to the Ping360 via UDP from the topside using [ping-python](https://github.com/bluerobotics/ping-python). There's [some example code in ping360.py](https://github.com/bluerobotics/ping-python/blob/deployment/brping/ping360.py#L279-L311) that can measure how fast you can expect to receive data with a given set of settings. If you use the same settings there as for your ROS setup you can determine whether it's a general sonar or Python issue, or if there are slowdowns from the ROS integration.

[This forum discussion](https://discuss.bluerobotics.com/t/ping-360-scan-speed-ros/9377) may also be worth a read.
